from __future__ import annotations


CONFIDENCE_STRONG = "stark"
CONFIDENCE_WEAK = "schwach"

MATCH_SOURCE_FUZZY = "fuzzy"
MATCH_SOURCE_KNOWLEDGE_BASE = "knowledge_base"
MATCH_SOURCE_KNOWLEDGE_BASE_MANUAL = "knowledge_base_manual"
MATCH_SOURCE_REJECTED = "rejected"
MATCH_SOURCE_UNMATCHED = "unmatched"

DIENT_SOURCE_STRONG = "strong"
DIENT_SOURCE_CONFIRMED = "manuell_bestaetigt"
DIENT_SOURCE_MANUAL = "manueller_link"

ALIAS_SOURCE_KIND_CONFIRMED_MATCH = "confirmed_match"
ALIAS_SOURCE_KIND_CONFIRMED_CANDIDATE = "confirmed_candidate"
ALIAS_SOURCE_KIND_MERGED_ENTITY = "merged_entity"

DOCUMENT_STATUS_PROCESSED = "processed"
DOCUMENT_STATUS_SKIPPED_UNCHANGED = "skipped_unchanged"
DOCUMENT_STATUS_NO_MATCHES = "no_matches"
DOCUMENT_STATUS_ERROR = "error"
DOCUMENT_STATUS_OPTIONS = [
    DOCUMENT_STATUS_PROCESSED,
    DOCUMENT_STATUS_SKIPPED_UNCHANGED,
    DOCUMENT_STATUS_NO_MATCHES,
    DOCUMENT_STATUS_ERROR,
]
